<robot name="gps" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="gps" params="parent">
        <xacro:property name="height1" value="0.02" />
        <xacro:property name="width" value="0.02" />
        <!-- Used for fixing robot to Gazebo 'base_link' -->

        <joint name="gps_link" type="fixed">
            <axis xyz="0 0 0" />
            <origin xyz="-0.15 0 0.2" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="sensor"/>
        </joint>

        <!-- Base Link -->
        <link name="sensor">
            <collision>
                <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>
                </geometry>
            </visual>

            <inertial>
                <origin xyz="0 0 1" rpy="0 0 0"/>
                <mass value="1e-4"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
        </link>



        <gazebo reference="sensor">
            <material>Gazebo/Red</material>
        </gazebo>

        <gazebo>
            <plugin name="gazebo_ros_gps" filename="libhector_gazebo_ros_gps.so">
                <alwaysOn>1</alwaysOn>
                <updateRate>14.0</updateRate>
                <!--bodyName>sensor</bodyName-->
                <bodyName>sensor</bodyName>
                <frameId>sensor</frameId>
                <topicName>/gps/fix</topicName>
                <velocityTopicName>/gps/fix_velocity</velocityTopicName>
                <referenceLatitude>-30.06022459407145675</referenceLatitude>
                <referenceLongitude>-51.173913575780311191</referenceLongitude>
                <referenceHeading>90</referenceHeading>
                <referenceAltitude>10</referenceAltitude>
                <offset>0 0 0</offset>
                <drift>0.001 0.001 0.001</drift>
                <gaussianNoise>0.05 0.05 0.05</gaussianNoise>
                <velocityDrift>0.001 0.001 0.001</velocityDrift>
                <velocityGaussianNoise>0.5 0.5 0.5</velocityGaussianNoise>
                <!--                <drift>0.001 0.001 0.001</drift>-->
                <!--                <gaussianNoise>0.01 0.01 0.01</gaussianNoise>-->
                <!--                <velocityDrift>0 0 0</velocityDrift>-->
                <!--                <velocityGaussianNoise>0.05 0.05 0.05</velocityGaussianNoise>-->
            </plugin>
        </gazebo>
    </xacro:macro>
</robot>